/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.utils.ConsoleHandler;
import org.example.utils.IHandler;
import org.example.utils.IceCreamMenu;

public class App {

    public static void main(String[] args) {
        IHandler handler = new ConsoleHandler();
        IceCreamMenu menu = new IceCreamMenu(handler);
        menu.displayMenu();
    }
}
